Repository mdsreq-fga-unb/2024.2-T03-CafeDoSitio, pull requests merged in 2024-11, with the labels that each got.

#1 Branch Oficial da Documentação
  .gitignore
  docs/assets/CafeSitioLogo.png
  docs/index.md
  docs/stylesheets/styles.css
  mkdocs.yml
Labels: documentation

#15 [DOC]: Incluir Tópico 2.1 e 2.2 no Docs
  docs/sections/2-docPage/2-solucaoProposta.md
Labels: documentation

#14 [DOC]: Incluir Tópico 1.3 e 1.4 no Docs
  docs/sections/2-docPage/1-cenarioAtual.md
Labels: documentation

#25 [DOC]: Incluir Tópico 1.3 e 1.4 no Docs
  docs/sections/2-docPage/1-cenarioAtual.md
Labels: documentation

#24 [DOC]: Incluir Página Inicial do Projeto
  docs/assets/BannerHome.png
  docs/assets/cafeDoSitio2_3.PNG
  docs/index.md
  mkdocs.yml
Labels: documentation

#27 [DOC]: Necessário acrescentar Atas da Sprint 1
  docs/assets/BannerDesenvolvedores.png
  docs/assets/BannerStakeholders.png
  docs/sections/2-docPage/4-cronogramaEntregas.md
  docs/sections/4-sprints/VisaoGeralBacklog.md
  docs/sections/4-sprints/sprint1/HistoricoBacklog.md
  docs/sections/4-sprints/sprint1/reuniões/[Equipe]04Nov2024.md
  docs/sections/4-sprints/sprint1/reuniões/[Stakeholders]04Nov2024.md
  docs/sections/4-sprints/sprint1/reuniões/[Stakeholders]06Nov2024.md
  docs/sections/4-sprints/sprint1/reuniões/[Stakeholders]07Nov2024.md
  mkdocs.yml
Labels: documentation

#17 [DOC]: Incluir Tópico 2.5 e 2.6 no Docs
  docs/assets/TabelaConhecimento.png
  docs/sections/2-docPage/2-solucaoProposta.md
Labels: documentation

#29 [DOC]: Documentação da Reunião de Equipe de Quinta (07/11/2024)
  docs/sections/2-docPage/4-cronogramaEntregas.md
  docs/sections/4-sprints/sprint1/reuniões/[Equipe]07Nov2024.md
  docs/sections/4-sprints/sprint1/reuniões/[Stakeholders]04Nov2024.md
  docs/sections/4-sprints/sprint1/reuniões/[Stakeholders]07Nov2024.md
  mkdocs.yml
Labels: documentation

#32 [DOC]: Documentação da Reunião de Equipe de Sexta (08/11/2024)
  docs/sections/4-sprints/sprint1/reuniões/[Equipe]08Nov2024.md
  mkdocs.yml
Labels: documentation

#37 [DOC]: Inserir Tópico 3 no GitPages
  docs/assets/processo_requisitados_cafe-do-sito.png
  docs/sections/2-docPage/3-estrategiasEngSoftware.md
Labels: documentation

#33 [DOC]: Incluir Tópico 1.1 e 1.2 no Docs
  docs/assets/DiagramaIshikawa.jpg
  docs/sections/2-docPage/1-cenarioAtual.md
  image.png
Labels: documentation

#36 [DOC]: Incluir tópico 2.4 no GitPages
  docs/sections/2-docPage/2-solucaoProposta.md
Labels: documentation

#40 [DOC]: Incluir tópico 5 no GitPages (Tópico 5.1)
  docs/sections/2-docPage/5-interacaoEquipeCliente.md
Labels: documentation

#35 [DOC]: Incluir tópico 5 no GitPages (Tópico 5.2)
  docs/sections/2-docPage/5-interacaoEquipeCliente.md
Labels: documentation

#43 [DOC]: Realizar revisão geral e Corrigir despadronizações
  docs/assets/DiagramaIshikawa.jpg
  docs/assets/DiagramaIshikawa.png
  docs/sections/2-docPage/1-cenarioAtual.md
  docs/sections/2-docPage/2-solucaoProposta.md
  docs/sections/2-docPage/3-estrategiasEngSoftware.md
  docs/sections/2-docPage/5-interacaoEquipeCliente.md
  docs/sections/4-sprints/sprint1/HistoricoBacklog.md
Labels: documentation

#51 [DOC]: Papéis e Responsabilidades
  docs/sections/2-docPage/5-interacaoEquipeCliente.md
Labels: product and project vision, improvement

#53 [DOC]: Estratégia de ESW
  docs/sections/2-docPage/3-estrategiasEngSoftware.md
Labels: product and project vision, improvement, question

#50 [DOC]: Figuras
  docs/assets/DiagramaIshikawa.jpg
  docs/assets/DiagramaIshikawa.png
  docs/assets/TabelaConhecimento.png
  docs/assets/TabelaConhecimentoPt1.png
  docs/assets/TabelaConhecimentoPt2.png
  docs/assets/gupta.png
  docs/sections/2-docPage/1-cenarioAtual.md
  docs/sections/2-docPage/2-solucaoProposta.md
  docs/sections/2-docPage/3-estrategiasEngSoftware.md
Labels: product and project vision

#52 [DOC]: Objetivos
  docs/sections/2-docPage/2-solucaoProposta.md
Labels: product and project vision, improvement

#79 [DOC]: Incluir Ata de Planning da Sprint 3 e Review da Sprint 2
  docs/sections/4-sprints/sprint1/reuniões/[Equipe]04Nov2024.md
  docs/sections/4-sprints/sprint2/reuniões/[Equipe]11Nov2024pt1.md
  docs/sections/4-sprints/sprint3/HistoricoBacklog.md
  docs/sections/4-sprints/sprint3/reuniões/[Equipe]18Nov2024pt1.md
  docs/sections/4-sprints/sprint3/reuniões/[Equipe]18Nov2024pt2.md
  mkdocs.yml
  package-lock.json
Labels: mettings documentation
