Repository mdsreq-fga-unb/2024.2-T03-CafeDoSitio, pull requests merged in 2024-12, with the labels that each got.

#84 [DOC]: Inserir ata do ciclo 4
  docs/sections/4-sprints/sprint4/HistoricoBacklog.md
  docs/sections/4-sprints/sprint4/reuniões/[Equipe]25Nov2024Pt1.md
  docs/sections/4-sprints/sprint4/reuniões/[Equipe]25Nov2024Pt2.md
  docs/sections/4-sprints/sprint4/reuniões/[Stakeholders]25Nov2024.md
  docs/sections/4-sprints/sprint4/reuniões/[Stakeholders]29Nov2024.md
  mkdocs.yml
Labels: mettings documentation

#90 [DOC]: Realizar o tópico 4.2 da Documentação no GitPages
  docs/sections/2-docPage/10-LicoesAprendidas.md
  docs/sections/2-docPage/4-engenhariaRequisitos.md
  docs/sections/2-docPage/5-cronogramaEntregas.md
  docs/sections/2-docPage/6-interacaoEquipeCliente.md
  mkdocs.yml
Labels: product and project vision

#85 [US18]: Consultar contatos da Empresa
  apps/backend/.env.template
  apps/backend/src/index.js
  apps/frontend/index.html
  apps/frontend/package.json
  apps/frontend/public/favicon.png
  apps/frontend/public/vite.svg
  apps/frontend/src/App.css
  apps/frontend/src/App.jsx
  apps/frontend/src/assets/FamiliaDoSitio.png
  apps/frontend/src/assets/FamiliaDoSitioBorda.png
  apps/frontend/src/assets/UnBLogo.png
  apps/frontend/src/assets/fonts/MyriadPro-Bold.woff
  apps/frontend/src/assets/fonts/MyriadPro-Bold.woff2
  apps/frontend/src/assets/fonts/MyriadPro-Regular.woff
  apps/frontend/src/assets/fonts/MyriadPro-Regular.woff2
  apps/frontend/src/assets/fonts/MyriadPro-Semibold.woff
  apps/frontend/src/assets/fonts/MyriadPro-Semibold.woff2
  apps/frontend/src/assets/react.svg
  apps/frontend/src/components/Footer/index.jsx
  apps/frontend/src/components/Footer/styled.js
  apps/frontend/src/components/Header/index.jsx
  apps/frontend/src/components/Header/styled.js
  apps/frontend/src/components/Paginacao/index.jsx
  apps/frontend/src/components/Paginacao/styled.js
  apps/frontend/src/components/RedButton/index.jsx
  apps/frontend/src/components/RedButton/styled.js
  apps/frontend/src/index.css
  apps/frontend/src/pages/ContactPage/index.jsx
  apps/frontend/src/pages/ContactPage/styled.js
  package-lock.json
  package.json
Labels: user story

#92 [DOC]: Realizar tópico 4.1 da Documentação no GitPages
  docs/sections/2-docPage/4-engenhariaRequisitos.md
  docs/sections/2-docPage/5-cronogramaEntregas.md
  docs/sections/2-docPage/6-interacaoEquipeCliente.md
  docs/sections/2-docPage/7-LicoesAprendidas.md
Labels: product and project vision

#98 [DOC]: Desenvolver tópico 9: Backlog do Produto
  docs/sections/2-docPage/7-LicoesAprendidas.md
  docs/sections/2-docPage/9-backlogDeProduto.md
  mkdocs.yml
Labels: product and project vision

#97 [DOC]: Desenvolver tópico 7: Requisitos de Software
  docs/sections/2-docPage/7-Requisitos.md
  docs/sections/2-docPage/9-backlogDeProduto.md
  mkdocs.yml
Labels: product and project vision

#101 [DOC]: Aperfeiçoar os nomes dos requisitos na seção 7 e 9
  docs/sections/2-docPage/7-Requisitos.md
  docs/sections/2-docPage/9-backlogDeProduto.md
Labels: product and project vision

#104 [US11]: Configurar disponibilidade de Visita
  apps/backend/.env.template
  apps/backend/src/controllers/sac.controller.js
  apps/backend/src/controllers/visita.controller.js
  apps/backend/src/middlewares/auth.middleware.js
  apps/backend/src/middlewares/sac.middleware.js
  apps/backend/src/models/Sac.js
  apps/backend/src/models/Visita.js
  apps/backend/src/routes/index.js
  apps/backend/src/routes/sac.route.js
  apps/backend/src/routes/visita.route.js
  apps/backend/src/services/nodemailer.service.js
  apps/backend/src/services/sac.service.js
  apps/backend/src/services/visita.service.js
  apps/frontend/src/App.jsx
  apps/frontend/src/components/BigPost/index.jsx
  apps/frontend/src/components/BigPost/styled.js
  apps/frontend/src/components/Header/index.jsx
  apps/frontend/src/components/Paginacao/index.jsx
  apps/frontend/src/components/Paginacao/styled.js
  apps/frontend/src/components/PublicLayout/index.jsx
  apps/frontend/src/components/PublicLayout/styled.js
  apps/frontend/src/components/SacSection/index.jsx
  apps/frontend/src/components/SacSection/styled.js
  apps/frontend/src/index.css
  apps/frontend/src/pages/(public)/BlogPage/index.jsx
  apps/frontend/src/pages/(public)/BlogPage/styled.js
  apps/frontend/src/pages/(public)/ContactPage/index.jsx
  apps/frontend/src/pages/(public)/ContactPage/styled.js
  apps/frontend/src/pages/(public)/nossaHistoria/index.jsx
  apps/frontend/src/pages/(public)/nossaHistoria/styled.js
  apps/frontend/src/routes/PublicRoutes.jsx
  apps/frontend/src/routes/RoutesConstants.jsx
  apps/frontend/src/services/sac.service.js
  apps/frontendAdmin/src/assets/Fabrica.jpg
  apps/frontendAdmin/src/components/AuthGuard/AuthGuard.jsx
  apps/frontendAdmin/src/components/Button/styled.js
  apps/frontendAdmin/src/components/DisponibilityCard/index.jsx
  apps/frontendAdmin/src/components/DisponibilityCard/styled.js
  apps/frontendAdmin/src/components/RedButton/index.jsx
  apps/frontendAdmin/src/components/RedButton/styled.js
  apps/frontendAdmin/src/components/SacCard/index.jsx
  apps/frontendAdmin/src/components/SacCard/styled.js
  apps/frontendAdmin/src/components/Tag/index.jsx
  apps/frontendAdmin/src/components/Tag/styled.js
  apps/frontendAdmin/src/pages/(private)/HomePage/index.jsx
  apps/frontendAdmin/src/pages/(private)/SacPage/index.jsx
  apps/frontendAdmin/src/pages/(private)/SacPage/styled.js
  apps/frontendAdmin/src/pages/(private)/VisitaCofigPage/index.jsx
  apps/frontendAdmin/src/pages/(private)/VisitaCofigPage/styled.js
  apps/frontendAdmin/src/pages/(private)/VisitaDetailsPage/index.jsx
  apps/frontendAdmin/src/pages/(private)/VisitaDetailsPage/styled.js
  apps/frontendAdmin/src/pages/(public)/LoginPage/index.jsx
  apps/frontendAdmin/src/routes/PrivateRoutes.jsx
  apps/frontendAdmin/src/routes/RoutesConstants.jsx
  apps/frontendAdmin/src/services/sac.service.js
  package-lock.json
  package.json
  packages/core/src/services/index.js
  packages/core/src/services/userService.js
  packages/core/src/services/visitaService.js
Labels: user story

#105 [DOC]: Desenvolver tópico 8: DoR e DoD
  .gitignore
  docs/sections/2-docPage/8-DoR&DoD.md
  mkdocs.yml
Labels: product and project vision

#102 [DOC]: Ajustar tópico 9 quanto à organização do Backlog e Prioridades
  docs/sections/2-docPage/4-engenhariaRequisitos.md
  docs/sections/2-docPage/5-cronogramaEntregas.md
  docs/sections/2-docPage/7-Requisitos.md
  docs/sections/2-docPage/9-backlogDeProduto.md
  docs/sections/4-sprints/VisaoGeralBacklog.md
  docs/sections/4-sprints/sprint1/reuniões/[Equipe]07Nov2024.md
  docs/sections/4-sprints/sprint1/reuniões/[Equipe]08Nov2024.md
  mkdocs.yml
Labels: product and project vision

#108 [DOC]: Inserir Atas do Ciclo 5 e 6 e corrigir calendário com as novas US's
  docs/sections/2-docPage/5-cronogramaEntregas.md
  docs/sections/4-sprints/sprint1/HistoricoBacklog.md
  docs/sections/4-sprints/sprint2/HistoricoBacklog.md
  docs/sections/4-sprints/sprint3/HistoricoBacklog.md
  docs/sections/4-sprints/sprint4/HistoricoBacklog.md
  docs/sections/4-sprints/sprint5/HistoricoBacklog.md
  docs/sections/4-sprints/sprint5/reuniões/[Equipe]09Dez2024Pt1.md
  docs/sections/4-sprints/sprint5/reuniões/[Equipe]09Dez2024Pt2.md
  docs/sections/4-sprints/sprint5/reuniões/[Stakeholders]06Dez2024.md
  docs/sections/4-sprints/sprint6/HistoricoBacklog.md
  docs/sections/4-sprints/sprint6/reuniões/[Equipe]16Dez2024.md
  docs/sections/4-sprints/sprint6/reuniões/[Stakeholders]13Dez2024.md
  mkdocs.yml
Labels: product and project vision
