Repository mdsreq-fga-unb/2024.2-T03-CafeDoSitio, pull requests merged in 2025-01, with the labels that each got.

#124 [DOC] Requisitos Funcionais, Requisitos Não Funcionais, Backlog - Épicos
  docs/sections/2-docPage/7-Requisitos.md
  docs/sections/2-docPage/9-backlogDeProduto.md
Labels: help wanted, improvement, question, requirements

#122 [DOC] Descricao das RQNF
  docs/sections/2-docPage/7-Requisitos.md
  docs/sections/2-docPage/9-backlogDeProduto.md
Labels: enhancement, mettings documentation

#126 [DOC] Correções na ER e na parte de Requisitos Funcionais no Backlog
  docs/sections/2-docPage/4-engenhariaRequisitos.md
  docs/sections/2-docPage/7-Requisitos.md
  docs/sections/2-docPage/9-backlogDeProduto.md
Labels: product and project vision

#130 [DOC] DoR & DoD
  .DS_Store
  docs/.DS_Store
  docs/sections/2-docPage/7-Requisitos.md
  docs/sections/2-docPage/8-DoR&DoD.md
  docs/sections/2-docPage/9-backlogDeProduto.md
Labels: product and project vision

#128 [DOC]: Inclusão do PBB e USM na documentação
  docs/sections/5-entregas/Unidade3/PBB.md
  docs/sections/5-entregas/Unidade3/USM.md
  mkdocs.yml
Labels: requirements

#131 [DOC] Requisitos não funcionais - Apenas referências para a produção
  docs/sections/2-docPage/4-engenhariaRequisitos.md
  docs/sections/2-docPage/7-Requisitos.md
Labels: product and project vision
