Repository mdsreq-fga-unb/2024.2-T03-CafeDoSitio, pull requests merged in 2025-02, with the labels that each got.

#138 [RQNF05]: As vagas de emprego da empresa devem ser exibidas de forma clara, com uma organização que facilitem a busca por oportunidades compatíveis com o interesse do usuário, instruindo o usuário como prosseguir com o processo no site terceiro empregare
  apps/frontend/src/pages/(public)/ContactPage/index.jsx
  apps/frontend/src/pages/(public)/ContactPage/styled.js
Labels: enhancement

#139 [US14]: Agendar Visita Presencial
  apps/backend/src/controllers/visita.controller.js
  apps/backend/src/models/Visita.js
  apps/backend/src/routes/index.js
  apps/backend/src/routes/visita.route.js
  apps/frontend/package.json
  apps/frontend/src/assets/VisitaTecnica.png
  apps/frontend/src/assets/VisitaTecnica2.png
  apps/frontend/src/assets/VisitaTecnica3.png
  apps/frontend/src/assets/VisitaTecnica4.png
  apps/frontend/src/assets/VisitaTecnica5.png
  apps/frontend/src/assets/VisitaTecnica6.png
  apps/frontend/src/assets/atencao.svg
  apps/frontend/src/assets/calendario.svg
  apps/frontend/src/assets/fonts/ImpactLTStd.woff
  apps/frontend/src/assets/fonts/ImpactLTStd.woff2
  apps/frontend/src/assets/visitaFabrica.jpg
  apps/frontend/src/components/Button/index.jsx
  apps/frontend/src/components/Button/styled.js
  apps/frontend/src/components/CustomCalendar/index.jsx
  apps/frontend/src/components/CustomCalendar/styled.js
  apps/frontend/src/components/DateInput/index.jsx
  apps/frontend/src/components/DateInput/styled.js
  apps/frontend/src/components/DisponibilityCard/index.jsx
  apps/frontend/src/components/DisponibilityCard/styled.js
  apps/frontend/src/components/Header/index.jsx
  apps/frontend/src/components/ModalVisita/index.jsx
  apps/frontend/src/components/ModalVisita/styled.js
  apps/frontend/src/components/RedButton/styled.js
  apps/frontend/src/components/Tag/index.jsx
  apps/frontend/src/components/Tag/styled.js
  apps/frontend/src/index.css
  apps/frontend/src/pages/(public)/VisitaFabricaPage/index.jsx
  apps/frontend/src/pages/(public)/VisitaFabricaPage/styled.js
  apps/frontend/src/routes/PublicRoutes.jsx
  apps/frontend/src/routes/RoutesConstants.jsx
  apps/frontendAdmin/src/pages/(private)/VisitaCofigPage/index.jsx
  apps/frontendAdmin/src/pages/(private)/VisitaCofigPage/styled.js
  apps/frontendAdmin/src/pages/(private)/VisitaDetailsPage/index.jsx
  apps/frontendAdmin/src/services/RouteConstant.js
  apps/frontendAdmin/src/services/sac.service.js
  package-lock.json
  package.json
  packages/core/src/services/RouteConstant.js
  packages/core/src/services/userService.js
  packages/core/src/services/visitaService.js
Labels: user story

#140 [RQNF03]: As informações sobre ações sociais da empresa devem estar disponíveis de maneira acessível e atrativa, garantindo clareza na comunicação e fácil navegação para o usuário.
  apps/frontend/src/App.jsx
  apps/frontend/src/assets/SítioVerde_1.jpg
  apps/frontend/src/assets/SítioVerde_6.jpg
  apps/frontend/src/assets/bazar.jpg
  apps/frontend/src/assets/grafico.png
  apps/frontend/src/assets/horta.jpg
  apps/frontend/src/assets/video.jpg
  apps/frontend/src/components/Header/index.jsx
  apps/frontend/src/components/MiniSticker/index.jsx
  apps/frontend/src/components/MiniSticker/styled.js
  apps/frontend/src/components/PublicLayout/index.jsx
  apps/frontend/src/components/Sticker/index.jsx
  apps/frontend/src/components/Sticker/styled.js
  apps/frontend/src/pages/(public)/SocialActionsPage/index.jsx
  apps/frontend/src/pages/(public)/SocialActionsPage/styeld.js
  apps/frontend/src/routes/PublicRoutes.jsx
  apps/frontend/src/routes/RoutesConstants.jsx
Labels: user story

#145 [BUG]: Identificador dos SAC deverá mudar para uma contagem incremental
  apps/backend/src/models/Counter.js
  apps/backend/src/models/Sac.js
  apps/frontendAdmin/src/components/SacCard/index.jsx
Labels: bug

#154 [BUG]: Unificação de ENV
  .env.template
  apps/backend/.env.template
  apps/backend/src/controllers/user.controller.js
  apps/backend/src/database/db.js
  apps/backend/src/index.js
  apps/backend/src/scripts/seeds.js
  apps/frontend/src/services/RouteConstant.js
  apps/frontend/src/services/sac.service.js
  apps/frontend/vite.config.js
  apps/frontendAdmin/src/pages/(public)/LoginPage/index.jsx
  apps/frontendAdmin/src/services/RouteConstant.js
  apps/frontendAdmin/src/services/sac.service.js
  apps/frontendAdmin/vite.config.js
  package-lock.json
  package.json
  packages/core/src/services/RouteConstant.js
  packages/core/src/services/userService.js
  packages/core/src/services/visitaService.js
Labels: bug

#152 [BUG]: Má comportamento no componente de história da Família do Sítio (Responsividade)
  apps/frontend/src/assets/1967.svg
  apps/frontend/src/assets/1972.svg
  apps/frontend/src/assets/1974.svg
  apps/frontend/src/assets/1986.svg
  apps/frontend/src/assets/1989.svg
  apps/frontend/src/assets/2000.svg
  apps/frontend/src/assets/2005.svg
  apps/frontend/src/assets/2009.svg
  apps/frontend/src/assets/2015.svg
  apps/frontend/src/assets/2017.svg
  apps/frontend/src/assets/2018.svg
  apps/frontend/src/assets/2025.svg
  apps/frontend/src/assets/Missão.svg
  apps/frontend/src/assets/celeirinho.png
  apps/frontend/src/components/TimelineCard/index.jsx
  apps/frontend/src/components/TimelineCard/styled.js
  apps/frontend/src/pages/(public)/nossaHistoria/index.jsx
  apps/frontend/src/pages/(public)/nossaHistoria/styled.js
Labels: bug

#156 [RQNF07]: A interface da página principal deverá introduzir os usuários às principais informações para as demais navegações: História da Família do Sítio e Ações Sociais, além do rodapé e cabeçalho com as demais navegações.
  apps/frontend/src/assets/Capa.jpg
  apps/frontend/src/assets/Fundocappuccino.jpg
  apps/frontend/src/assets/cappuccino.png
  apps/frontend/src/assets/inicial1.jpg
  apps/frontend/src/assets/inicial2.jpg
  apps/frontend/src/assets/topo.jpeg
  apps/frontend/src/components/Header/index.jsx
  apps/frontend/src/components/PublicLayout/index.jsx
  apps/frontend/src/pages/(public)/BlogPage/index.jsx
  apps/frontend/src/pages/(public)/BlogViewPage/index.jsx
  apps/frontend/src/pages/(public)/ContactPage/index.jsx
  apps/frontend/src/pages/(public)/MainPage/index.jsx
  apps/frontend/src/pages/(public)/MainPage/styled.js
  apps/frontend/src/pages/(public)/SocialActionsPage/index.jsx
  apps/frontend/src/pages/(public)/VisitaFabricaPage/index.jsx
  apps/frontend/src/pages/(public)/nossaHistoria/index.jsx
  apps/frontend/src/routes/PublicRoutes.jsx
  apps/frontend/src/routes/RoutesConstants.jsx
  package-lock.json
  package.json
Labels: user story

#158 [BUG]: Remover lixeira do administrador do sistema no gerenciamento de conta
  apps/frontendAdmin/src/pages/(private)/AdminAccountsPage/index.jsx
Labels: bug

#157 [US16]: Localizar Produtos
  apps/backend/src/controllers/estabelecimento.controller.js
  apps/backend/src/controllers/produto.controller.js
  apps/backend/src/controllers/sac.controller.js
  apps/backend/src/controllers/user.controller.js
  apps/backend/src/models/Estabelecimento.js
  apps/backend/src/models/Produto.js
  apps/backend/src/routes/estabelecimento.route.js
  apps/backend/src/routes/index.js
  apps/backend/src/routes/produto.route.js
  apps/backend/src/services/estabelecimento.service.js
  apps/backend/src/services/produto.service.js
  apps/frontend/index.html
  apps/frontend/src/assets/DetalhesNossosProdutos/3.png
  apps/frontend/src/assets/DetalhesNossosProdutos/4.png
  apps/frontend/src/assets/DetalhesNossosProdutos/Nossos-Produtos_assumnovo.png
  apps/frontend/src/assets/DetalhesNossosProdutos/Nossos-Produtos_specialenovo.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutosSelosABIC_4.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_assumpreto_1.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_assumpreto_2.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_assumpreto_3.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_assumpreto_3_copia.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_assumpreto_4.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_assumpreto_4_copia.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_familiadositio_1.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_familiadositio_1novo.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_familiadositio_2.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_familiadositio_cafevacuo.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_familiadositio_capuccino.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_familiadositio_gourmet.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_speciale_1.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_speciale_2.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_speciale_3.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_speciale_4.png
  apps/frontend/src/assets/DetalhesNossosProdutos/NossosProdutos_speciale_5.png
  apps/frontend/src/assets/DetalhesNossosProdutos/selopureza.png
  apps/frontend/src/components/Header/index.jsx
  apps/frontend/src/components/MiniSticker/styled.js
  apps/frontend/src/components/PertodeVoce/index.jsx
  apps/frontend/src/components/PertodeVoce/styled.js
  apps/frontend/src/components/PublicLayout/index.jsx
  apps/frontend/src/components/SmallPost/index.jsx
  apps/frontend/src/components/SmallPost/styled.js
  apps/frontend/src/index.css
  apps/frontend/src/pages/(public)/ContactPage/index.jsx
  apps/frontend/src/pages/(public)/nossaHistoria/index.jsx
  apps/frontend/src/pages/(public)/nossosProdutos/ImgContent/index.jsx
  apps/frontend/src/pages/(public)/nossosProdutos/ImgContent/styled.js
  apps/frontend/src/pages/(public)/nossosProdutos/index.jsx
  apps/frontend/src/pages/(public)/nossosProdutos/styled.js
  apps/frontend/src/pages/(public)/nossosProdutosInfo/index.jsx
  apps/frontend/src/pages/(public)/nossosProdutosInfo/styled.js
  apps/frontend/src/routes/PublicRoutes.jsx
  apps/frontend/src/routes/RoutesConstants.jsx
  apps/frontend/src/services/produto.service.js
  package-lock.json
  package.json
Labels: user story

#162 [BUG]: Falta de interação com o botão de Perfil no painel administrativo
  apps/backend/src/controllers/user.controller.js
  apps/backend/src/routes/user.route.js
  apps/backend/src/services/user.service.js
  apps/frontendAdmin/package.json
  apps/frontendAdmin/src/components/Header/index.jsx
  apps/frontendAdmin/src/pages/(private)/EditAccountPage/index.jsx
  apps/frontendAdmin/src/pages/(private)/EditAccountPage/styled.js
  apps/frontendAdmin/src/routes/PrivateRoutes.jsx
  apps/frontendAdmin/src/routes/RoutesConstants.jsx
  package-lock.json
  package.json
  packages/core/src/index.js
  packages/core/src/services/userService.js
Labels: bug

#151 [BUG]: Logo da Família do Sítio (Cabeçalho) não contrasta com o modo escuro. ||| [BUG]: Mudar cores do fundo do Menu Mobile
  apps/frontend/src/assets/FamiliaDoSitioBorda.png
  apps/frontend/src/components/Header/index.jsx
  apps/frontend/src/components/Header/styled.js
Labels: bug

#165 Docs/bd ds correcoes
  docs/sections/2-docPage/9-backlogDeProduto.md
  docs/sections/5-entregas/Unidade3/PBB.md
Labels: product and project vision

#164 [BUG]: Envio de emails não está enviando emails
  .env.template
  apps/backend/src/controllers/sac.controller.js
  apps/backend/src/services/nodemailer.service.js
  apps/frontend/src/components/SacSection/index.jsx
  apps/frontend/src/pages/(public)/ContactPage/index.jsx
  apps/frontend/src/pages/(public)/nossosProdutos/index.jsx
Labels: bug

#175 [BUG] - Marcador de localização do usuário não carrega o icone
  apps/frontend/src/assets/SítioVerde_2.jpg
  apps/frontend/src/assets/video.jpg
  apps/frontend/src/components/PertodeVoce/index.jsx
  apps/frontend/src/pages/(public)/SocialActionsPage/index.jsx
Labels: bug
